sudo: required
services:
  - docker

before-install:
  - docker build -t bindulathanuthalapati/docker-react -f Dockerfile.dev .

script:
  - docker run bindulathanuthalapati/docker-react npm run test -- --coverage